#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3.7'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  java:
    build: .

    # Uncomment if you want to expose any additional ports. The snippet below exposes port 3000.
    # ports:
    #   - 3000:3000
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

      # Uncomment the next line if you plan to install the Docker CLI. See the docker-in-docker-compose definition for details.
      # - /var/run/docker.sock:/var/run/docker.sock 

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    secrets:
      - source: ssh-key
        uid: '103'
        gid: '103'
        mode: 0440
      - ssh-pub-key
      - hosts

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 
 
secrets:
  ssh-key:
    file: C:\Users\m_mil\.ssh\id_rsa
  ssh-pub-key:
    file: C:\Users\m_mil\.ssh\id_rsa.pub
  hosts:
    file: C:\Users\m_mil\.ssh\known_hosts